FROM docker/compose:debian-1.25.4

RUN apt update
RUN apt install --yes \
    git \
    netcat \
    curl \
    net-tools

WORKDIR /app

ENV LATEST_COMMIT_AT_THE_TIME_OF_DOCKERIZATION=2ff2f2ec12e214a741e8df1c395b96f1501c5e7b

RUN git clone -n https://github.com/getsentry/onpremise.git ./
RUN git checkout ${LATEST_COMMIT_AT_THE_TIME_OF_DOCKERIZATION}

COPY bin/ ./

EXPOSE 9000

ENTRYPOINT ["./entrypoint.sh"]

CMD ["start"]